config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/home/index', to: 'home#index'
  get '/home/test', to: 'home#test'
  post '/home/guest_sign_in', to: 'home#new_guest'
  
  get '/youtube/match_playlist', to: 'youtube#match_playlist'
  get '/youtube/user_playlist', to: 'youtube#user_playlist'
   resources :youtube
    
  

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks",
  } 
  
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/models/youtube.rb
class Youtube < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
  before_action :authenticate_user!
  
  GOOGLE_API_KEY = Rails.application.credentials.google[:api_key]

  def index
    
  end

  def new
    @playlist_video = current_user.youtubes.build
  end

  def create
    # APIで取得した動画のうち、view側で指定したものだけを保存する
    @playlist_video = current_user.youtubes.create(
      specific_id: params[:specific_id],
      video_id: params[:video_id],
      playlist_id: params[:playlist_id],
      title: params[:title],
      description: params[:description],
      user_id: current_user.id
    )
    if @playlist_video.save
      redirect_to @playlist_video, notice: "「#{@playlist_video.title}」をPlaylistに追加しました"
    end
  end

  def show
    @playlist_video = current_user.youtubes.find(params[:id])
  end

  def destroy
    playlist_video = current_user.youtubes.find(params[:id])
    if playlist_video.destroy
      redirect_to youtube_user_playlist_path, alert: "「#{playlist_video.title}」をリストから削除しました"
    end
  end

  def match_playlist
    # paramsが空だとAPIメソッドがエラーとなってしまうので回避
    params[:playlist_id].blank? ? @playlist_videos = playlist_videos('PLQ6aFfQOcQBO2zPgf9ru4_DDuNFmycpQa') : @playlist_videos = playlist_videos(params[:playlist_id])
  end

  def user_playlist
    @playlist_videos = current_user.youtubes.page(params[:page])
  end


  private
  
  def playlist_videos(playlist_id)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY
    next_page_token = nil
    opt = {
      playlist_id: playlist_id,
      max_results: 100,
      page_token: next_page_token,
    }
    begin
      results = service.list_playlist_items(:snippet, opt)
      results_items = results.to_h
      search_results = results_items[:items]   
      
      if search_results.blank?
        return
      end

    
    rescue Google::Apis::YoutubeV3::YouTubeService => err
      puts "YoutubeAPIからの動画取得に問題が発生しました"
      puts err.results.body
    end
    return search_results
  end

end

app/views/youtube/_feelingbox.html.haml
%section.pb-50#select-box
  ///// Header MenuBlock /////
  %header.pt-80.pb-10.bg-dark.op-9.header_2
    / Header MenuBlock
    .col-md-4{"data-aos" => "fade-down", "data-aos-delay" => "900", "data-aos-duration" => "600"}
      .container
        .logo.color-white MVページ
    .container
      .mw-620.mx-auto.mt-10.f-22.color-white.op-9.text-center.text-adaptive
        %span{"data-aos" => "fade-down", "data-aos-delay" => "300", "data-aos-duration" => "600"}
        今の「気分」を以下のボックスから選択しよう！
    .container
      / ICON BOXES
      %section#icon-boxes.p-5
        .container 
          / 1行目
          .row.mb-4
            .col-md-4
              .card.bg-danger.text-white.text-center
                .card-body
                  %i.fas.fa-smile.fa-3x
                  %h4 元気になりたい
                  テンションが上がるMV
                  %br
                  = link_to youtube_match_playlist_path(playlist_id: 'PLQ6aFfQOcQBO2zPgf9ru4_DDuNFmycpQa') do
                    %i.fab.fa-youtube.fa-3x
            .col-md-4
              .card.bg-info.text-white.text-center
                .card-body
                  %i.fas.fa-coffee.fa-3x
                  %h4 ゆったりひととき
                  一息ついて落ち着きたいときのMV
                  %br
                  = link_to youtube_match_playlist_path(playlist_id: 'PLQ6aFfQOcQBPjwabrsAf5cH7UL51X0ODA') do
                    %i.fab.fa-youtube.fa-3x
            .col-md-4
              .card.bg-warning.text-white.text-center
                .card-body
                  %i.fab.fa-apple.fa-3x
                  %h4 色鮮やか
                  綺麗で脳が活性化するMV
                  %br
                  = link_to youtube_match_playlist_path(playlist_id: 'PLQ6aFfQOcQBMaKVnqNEiF-8FxEYCAqJpK') do
                    %i.fab.fa-youtube.fa-3x
          / 2行目
          .row.mb-4
            .col-md-4
              .card.bg-success.text-white.text-center
                .card-body
                  %i.fas.fa-hat-wizard.fa-3x
                  %h4 幻想的な世界へ
                  不思議で幻想的な世界に入れるMV
                  %br
                  = link_to youtube_match_playlist_path(playlist_id: 'PLQ6aFfQOcQBNVNfg1k9dtNDF-x0DLvPfH') do
                    %i.fab.fa-youtube.fa-3x
            .col-md-4
              .card.bg-secondary.text-white.text-center
                .card-body
                  %i.fas.fa-headphones-alt.fa-3x
                  %h4 やみつきメロディ
                  コードや音階がやみつきになる。リピート必至のMV。
                  %br
                  = link_to youtube_match_playlist_path(playlist_id: 'PLQ6aFfQOcQBO6z6usNEPeGudbOtXQ7IqF') do
                    %i.fab.fa-youtube.fa-3x
            .col-md-4
              .card.bg-secondary.text-white.text-center
                .card-body
                  %i.fas.fa-globe-americas.fa-3x
                  %h4 なんか洋楽
                  とりあえず洋楽聴きたいときのMV
                  %br
                  = link_to youtube_match_playlist_path(playlist_id: 'PLQ6aFfQOcQBMVQBqb0svBMXPH5EYIcEtp') do
                    %i.fab.fa-youtube.fa-3x

/ MVリストのタイトル
- case params[:playlist_id]
  - when "PLQ6aFfQOcQBO2zPgf9ru4_DDuNFmycpQa" then
    %h3 元気になれるMV
  - when "PLQ6aFfQOcQBPjwabrsAf5cH7UL51X0ODA" then
    %h3 ゆったり落ち着けるMV
  - when "PLQ6aFfQOcQBMaKVnqNEiF-8FxEYCAqJpK" then
    %h3 色鮮やかなMV
  - when "PLQ6aFfQOcQBNVNfg1k9dtNDF-x0DLvPfH" then
    %h3 幻想的な世界観のMV
  - when "PLQ6aFfQOcQBO6z6usNEPeGudbOtXQ7IqF" then
    %h3 やみつきメロディMV
  - when "PLQ6aFfQOcQBMVQBqb0svBMXPH5EYIcEtp" then
    %h3 とりあえず洋楽のMV

app/views/youtube/index.html.haml
.top-page
  .bg-mask
    .container
      = render 'shared/message'
      #section.pt-40
        = render 'feelingbox'
  

app/views/youtube/match_playlist.html.haml
.top-page
  .bg-mask
    .container
      #section.pt-40
        = render 'feelingbox'
        = render 'shared/message'

      %section.pt-40.pb-100
        -# セレクトボックスで選択したプレイリストの動画を表示
        .row
          - @playlist_videos.each do |item|
            .col-sm-6.col-md-4
              .card.img-thumbnail
                .embeded-video-responsive
                  %div
                    %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "220", :src => "https://www.youtube.com/embed/#{item[:snippet][:resource_id][:video_id]}", :width => "340"}
                .card-body.px-2.py-3
                  %h5.card-title= item[:snippet][:title]
                  %p.card-text
                    = item[:snippet][:published_at]
                    %br
                    %strong
                      = "Playlistに保存"
                    = link_to youtube_index_path(specific_id: item[:id], title: item[:snippet][:title], video_id: item[:snippet][:resource_id][:video_id], playlist_id: item[:snippet][:playlist_id], description: item[:snippet][:description][0..1024]), :method => :post do 
                      %i.far.fa-file-video.fa-2x
              %br

app/views/youtube/show.html.haml
.top-page
  .bg-mask
    .container
      #section.pt-40.pb-100
        = render 'shared/message'
        .row  
          .col-sm-6.col-md-6
            .card.img-thumbnail
              .embeded-video-responsive
                %div
                  %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :playsinline => "1", :allowfullscreen => "", :frameborder => "0", :height => "220", :src => "https://www.youtube.com/embed/#{@playlist_video[:video_id]}?playsinline=1", :width => "340"}
              .card-body.px-2.py-3
                %h5.card-title= @playlist_video[:title]
                %p.card-text
                  = @playlist_video[:published_at]
          .col-sm-6.md-6
            .card.img-thumbnail
              .card-body.px-2.py-3
                %p
                  %strong= "アーティスト名 -曲名"
                  %br
                  = @playlist_video.title
                  %br
                  %br
                  %strong= "動画概要(Youtubeの概要欄を転載)"
                  %br
                  .grad-wrap
                  %input#trigger1.grad-trigger{:type => "checkbox"}
                  .grad-item
                    -# 改行文字\nを<br>タグに変換
                    = simple_format(@playlist_video.description)
                  %label.grad-btn{:for => "trigger1"}
        %br
        = link_to youtube_match_playlist_path(playlist_id: @playlist_video.playlist_id) do
          %button.btn.action-1.lg MVページへ行く
        = link_to youtube_user_playlist_path do
          %button.btn.action-3.lg Playlistページへ行く

app/views/youtube/user_playlist.html.haml
.top-page
  .bg-mask
    %section.pt-40.pb-100
      .container
        = render 'shared/message'
        
        %h3= "#{current_user.username}さんのPlaylist!"
        %br
        .row
          - @playlist_videos.each do |item|
            .col-sm-6.col-md-4
              .card.img-thumbnail
                .embeded-video-responsive
                  %div
                    %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "220", :src => "https://www.youtube.com/embed/#{item[:video_id]}", :width => "340"}
                .card-body.px-2.py-3
                  %h5.card-title= item[:title]
                  %p.card-text
                    = item[:published_at]
                  %br
                  = link_to youtube_path(item) do 
                    %button.btn-outline-primary 詳細
                  = link_to youtube_path(item), :method => :delete do 
                    %button.btn-outline-danger 削除
              %br
          = paginate @playlist_videos