config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/home/index', to: 'home#index'
  get '/home/test', to: 'home#test'
  post '/home/guest_sign_in', to: 'home#new_guest'
  
  get '/youtube/match_playlist', to: 'youtube#match_playlist'
  get '/youtube/user_playlist', to: 'youtube#user_playlist'
   resources :youtube
    
  

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks",
  } 
  
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/views/shared/_message.html.haml
- unless flash.empty?
  %script{:type => 'text/javascript'}
    - flash.each do |f|
      - type = f[0].to_s.gsub('alert','error').gsub('notice','info')
      :erb
        toastr['<%= type%>']('<%= f[1]%>');

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "/"}
          %i.fas.fa-headphones-alt.fa-2x
          = image_tag '/images/logo1.jpg', alt: 'アプリロゴ',　class: 'navbar-logo'
          %span.sr-only (current)
      %li.nav-item
        - if user_signed_in?
          = link_to "ホーム画面", root_path, class: "a nav-link"
        - else
          = link_to "アプリ紹介画面", root_path, class: "a nav-link"
      %li.nav-item
        %a.nav-link{:href => "/youtube"} MV
      - if user_signed_in?
        %li.nav-item  
          = link_to "Playlist", youtube_user_playlist_path, class: "a nav-link"
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          ユーザー
        - if user_signed_in?
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            = link_to "プロフィール", edit_user_registration_path , class: "a dropdown-item"
            = link_to "ログアウト", logout_path , class: "a dropdown-item"
            .dropdown-divider
            %a.dropdown-item{:href => "#"} おまけ？
        - else
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            = link_to "ユーザ登録", signup_path , class: "a dropdown-item"
            = link_to "ログイン", login_path , class: "a dropdown-item"
            .dropdown-divider
            %a.dropdown-item{:href => "#"} おまけ？
    %ul.navbar-nav
      %li.nav-item
        - if user_signed_in?
          %strong
            %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"}= "#{current_user.username}さん、ようこそ"
        - else
          %strong
            %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"}= "未ログイン状態です"